### ISSUE TITLE
Povider produces a error in some search

### ISSUE THREAD

**Issue by Pacolo** [mancuniancol/script.pulsar.kickass-mc#1]
When I search "tronos" the provider produces an error: ERROR parsing data

But if I search "Interstellar" it works.

**Comment by mancuniancol** [comment]
Could you provide me your log through pastebin.com?

**Comment by Pacolo** [comment]
http://pastebin.com/ERWBp5Hs

**Comment by mancuniancol** [comment]
It seems that the problem is the name of the files doesn't respect the TV show format s00e00.

**Comment by mancuniancol** [comment]
But, I will try to do something

**Comment by mancuniancol** [comment]
I've found the problem. The script has problem with the "ñ".  I will try to fix it (again)
