### ISSUE TITLE
TV Shows not working with the new SSL implementation

### ISSUE THREAD

**Issue by imranismail** [mancuniancol/script.pulsar.kickass-mc#1]

**Comment by mancuniancol** [comment]
Could I have your log?

**Comment by ThePuner** [comment]
script.module.pyopenssl only supports OSX py2.6 win32 py2.6 win32 py2.7 linux-x86_64 py2.6.
Please consider using human_curl as suggested here https://github.com/andrewleech/script.module.pyopenssl/issues/1#issuecomment-143077501 (has arm build)

**Comment by mancuniancol** [comment]
Well,  I've tried to use it but I have  an error:

  File "C:\Users\mancuniancol\AppData\Roaming\Kodi\addons\script.module.pycurl\lib\pycurl\__init__.py", line 49, in __bootstrap__
                                                imp.load_dynamic(__package,__file)
                                            ImportError: DLL load failed: The specified module could not be found.

It seems that it doesn't work under windows.

I don't have problem to use it, but I don't have time to fix it.   :(

**Comment by mancuniancol** [comment]
I still think that it is better to use http mirrors  from kickass instead of https.

**Comment by ThePuner** [comment]
Can you modify it so openssl won't be imported or used if the url scheme is http? That way android arm users could still use it by changing the url in settings.

**Comment by mancuniancol** [comment]
Well.. it is too complicated to be honest.  I've changed the library.  Now, it is httpbli2 that is cross platform.  you can download the dependency from http://mirror.lstn.net/kodi/addons/gotham/script.module.httplib2/script.module.httplib2-0.8.0.zip

Any case, let me know if it works for you.  Otherwise, I will give the option to choose

**Comment by ThePuner** [comment]
Well done, it works.
