### ISSUE TITLE
Error parsing data

### ISSUE THREAD

**Issue by jorritsmit** [mancuniancol/script.pulsar.kickass-mc#2]
Hey,  
i think i have a problem with the httplib2. When looking for torrents the common.browser object returns an error. Error parsing data. The eztv provider gives a similar error. Non recoverable failure in name resolution in the urlib2.py.

I am running kodi on an arm Android box.

**Comment by mancuniancol** [comment]
Yesterday, I've already released a fix. Have you still having trouble with that?

**Comment by mancuniancol** [comment]
Any case, FYI, the parsing error I've added when the structure of the website changes.

**Comment by jorritsmit** [comment]
yeah i still seem to have the problem after installing 3.09 (manually btw). i am using the superrepo repo  of you add on. i have done some more research and the parsing error only occurs when numbers are involved. When i use pulsars direct torrent search function and no numbers are invovled, your provider works. When i use a capital letter (E02) i get an 404 error.

**Comment by jorritsmit** [comment]
i'll gather some logs and provide them soon

**Comment by mancuniancol** [comment]
Please, that it will be really useful. Because, I cannot reproduced your issue yet.

**Comment by jorritsmit** [comment]
i haven't been able to repeproduce the errors after your last updates. Thanks!
